rules = (("And They Shall Know No Fear", "Automatically pass regroup tests"),
         ("Armourbane", "2d6 for armor penetration rolls against vehicles"),
         ("Blast", "3 inch template on hit, scatters by 2d6 - BS"),
         ("Counterattack", "If charged and passed leadership, unit gets +1 attack"),
         ("Daemon", "5+ invuln save and Fear"),
         ("Eternal Warrior", "Cannot be instantly killed"),
         ("Feel No Pain", "'Ignores' unsaved wounds on a 5+"),
         ("Fleshbane", "Wounds on 2+, no effect on vehicles"),
         ("Furious Charge", "+1 str on charge"),
         ("Ignores Cover", "No cover saves allowed"),
         ("Instant Death", "Unsaved wounds cause instant death"),
         ("Melta", "If within range/2, add 1d6 to armor penetration"),
         ("Missile Lock", "Scatter is only 1d6"),
         ("Poisoned", "always wounds on 4+. If Str of wielder >= Tou of victim, reroll failed wounds in melee"),
         ("Rending", "If to wound roll = 6, no armor save. Against vehicles, on AP roll of 6, add 1d3 to the result as well"),
         ("Shred", "Reroll failed To Wound rolls"),
         ("Sniper", "Always wounds on 4+, as well as Rending"),
         ("Twin Linked", "Normal - Reroll failed To Hit rolls, Template - Reroll failed To Wound and AP rolls"),
         ("Unwieldy", "Init = 1 unless walker or MC"))
